using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
public class Levelselector : MonoBehaviour
{
    public Text buildingname;
    public Text buildingaddress;
    public GameObject ContentPanel;
    public GameObject ListItemPrefab;

    ArrayList RoomList;

    private Panel_ManagerScript PMS;
    public Animator Animator;
    private Sprite libraryimg;
    private Sprite Fengineeringimg;
    private Sprite SSimg;
    private Sprite Mainimg;
    public Image img;

    public SceneFader fader;
    private Text BuildingName;
    private string BN;
    void Start()
    {

        PMS = GameObject.Find("PanelAnimationManager").GetComponent<Panel_ManagerScript>();
        BuildingName = GameObject.Find("buildingname").GetComponent<Text>();
        libraryimg = Resources.Load<Sprite>("Sprites/LibraryImage");
        Fengineeringimg = Resources.Load<Sprite>("Sprites/Fengineeringbuilding");
        SSimg = Resources.Load<Sprite>("Sprites/SSimage");
        Mainimg = Resources.Load<Sprite>("Sprites/mainbuildingimg");

        buildingname.text = "뭐야";

    }
    public void Select()
    {
        BN = BuildingName.text;//BuildingName.text;
        switch (BN)
        {
            case "퇴계기념중앙도서관":
                PMS.MoreDetailEnableBoolAnimator(Animator);
                img.sprite = libraryimg;
                buildingname.text = "퇴계기념중앙도서관";
                buildingaddress.text = "경기도 용인시 수지구 죽전동 126";
                RoomList = new ArrayList()
                {
new Room("103호", "1열람실"),
new Room("110호", "1보존서고"),
new Room("001호", "현금지급기"),
new Room("201호", "대학원열람실"),
new Room("202호", "4열람실"),
new Room("205호", "휴게실"),
new Room("206호", "매점"),
new Room("207호", "저수조"),
new Room("211호", "2열람실"),
new Room("212호", "3열람실"),
new Room("301호", "전자정보자료실"),
new Room("301-1호", "멀티미디어룸"),
new Room("302호", "자율 학습 라운지"),
new Room("303호", "세미나실"),
new Room("304호", "교수학습개발센터 사무실"),
new Room("305호", "교수학습개발센터장실"),
new Room("306호", "교수학습역량강화세미나실"),
new Room("307호", "CTL허브"),
new Room("308호", "수위실"),
new Room("310호", "출판부사무실"),
new Room("311호", "출판부장실"),
new Room("312호", "도서관장실"),
new Room("313호", "부속실"),
new Room("314호", "창고"),
new Room("315호", "방송실"),
new Room("316호", "다목적실"),
new Room("317호", "수서창고"),
new Room("318호", "3보존서고"),
new Room("319호", "대출실"),
new Room("320호", "도서관사무실"),
new Room("0001호", "자동심장충격기(경비실 옆)"),
new Room("401호", "자연과학실"),
new Room("402호", "2인문과학실"),
new Room("403호", "복사실"),
new Room("404호", "그룹스터디룸4-3"),
new Room("405호", "그룹스터디룸4-2"),
new Room("406호", "그룹스터디룸4-1"),
new Room("407호", "1인문과학실"),
new Room("408호", "4보존서"),
new Room("409호", "학위논문실"),
new Room("501호", "예체능실"),
new Room("502호", "2사회과학실"),
new Room("503호", "그룹스터디룸5-4"),
new Room("504호", "그룹스터디룸5-3"),
new Room("505호", "그룹스터디룸5-2"),
new Room("506호", "그룹스터디룸5-1"),
new Room("507호", "1사회과학실"),
new Room("508호", "5보존서고"),
new Room("509호", "고문헌실"),
new Room("601호", "동양학자료실"),
new Room("602호", "2정기간행물실"),
new Room("603호", "동양학연구원장실"),
new Room("604호", "편찬실,연구기획팀"),
new Room("605호", "고전번역연구실"),
new Room("606호", "그룹스터디룸6-4"),
new Room("607호", "그룹스터디룸6-3"),
new Room("608호", "그룹스터디룸6-2"),
new Room("609호", "그룹스터디룸6-1"),
new Room("610호", "1정기간행물실"),
new Room("611호", "3정기간행물실"),
new Room("612호", "6보존서고")
                };

                break; //fader.FadeTo("Library"); 

            case "제1 공학관":
                PMS.MoreDetailEnableBoolAnimator(Animator);
                img.sprite = Fengineeringimg;
                buildingname.text = "제1 공학관";
                buildingaddress.text = "경기도 용인시 수지구 죽전로 152(죽전동)";
                RoomList = new ArrayList()
                {
                    new Room("101호", "경기도 단국-삼성모바일연구소"),
new Room("102호", "경기도 단국-삼성모바일연구소"),
new Room("103호", "고지능구조기술실험실"),
new Room("104호", "건축대학 학생회실"),
new Room("105호", "강의실"),
new Room("106호", "기계공학과세미나실"),
new Room("107호", "재료실험실1"),
new Room("108호", "재료실험실2"),
new Room("109호", "유체역학실험실"),
new Room("110호", "기계공학종합실험실"),
new Room("111호", "연소공학실험실"),
new Room("112호", "강의실"),
new Room("113호", "건축공학인증자료"),
new Room("113-1호", "건축학 인증 자로실"),
new Room("202호", "토목환경종합설계실"),
new Room("203호", "기기실"),
new Room("204호", "토질역학실험준비실"),
new Room("205호", "토질역학실험실"),
new Room("206호", "측략실험실/토목환경"),
new Room("207호", "박성완"),
new Room("208호", "이정휘"),
new Room("210호", "정철헌"),
new Room("211호", "박재균"),
new Room("212호", "강부식"),
new Room("213호", "조완제"),
new Room("214호", "토목환경공학과 사무실"),
new Room("215호", "토목기기실"),
new Room("216호", "김두일"),
new Room("217호", "수공학실험실"),
new Room("218호", "정역학실험준비"),
new Room("219호", "토목환경공학과 세미나실"),
new Room("220호", "하천정보연구실"),
new Room("221호", "상수도공학실험실"),
new Room("222호", "정역학실험실"),
new Room("223호", "철근콘크리트실험준비실"),
new Room("224호", "철근콘크리트실험실"),
new Room("225호", "실험체양생실"),
new Room("226호", "기기실"),
new Room("227호", "환경공학실험실"),
new Room("228호", "환경공학실험실"),
new Room("229호", "환경공학실험준비실"),
new Room("0001", "자동심장충격기(입구)"),
new Room("301호", "건축대학 학장실"),
new Room("302호", "건축대학 교학행정팀"),
new Room("303호", "건축공학과사무실"),
new Room("304호", "준비실"),
new Room("305호", "건축공학 자료보관실 및 도서관"),
new Room("306호", "초고층빌딩 글로벌 R&BD센터 기술개발실"),
new Room("307호", "세미나실"),
new Room("308호", "문현준"),
new Room("309호", "이상현"),
new Room("310호", "민경원"),
new Room("311호", "전재열"),
new Room("312호", "박태원"),
new Room("313호", "이경구"),
new Room("314호", "엄태성"),
new Room("315호", "김치경"),
new Room("316호", "김준희"),
new Room("317호", "리모델링연구소 및 초고층빌딩 글로벌 R&BD센터 기술인증실"),
new Room("318호", "건축공학과스튜디오5"),
new Room("319호", "건축공학과스튜디오3"),
new Room("320호", "건축공학과스튜디오4"),
new Room("321호", "건축공학전산실1"),
new Room("322호", "리모델링연구소/디지털리모델링기술연구실"),
new Room("323호", "건축공학전산실2"),
new Room("324호", "건축학과 스튜디오1"),
new Room("325호", "건축디지털미디어실"),
new Room("326호", "건축대학문헌정보실"),
new Room("327호", "건축학과 모형제작실"),
new Room("327-1호", "건축학과 사진실"),
new Room("328호", "건축학과 스튜디오2"),
new Room("329호", "건축학과 스튜디오3"),
new Room("401호", "건축학과 스튜디오"),
new Room("401-1호", "건축학과 스튜디오5"),
new Room("401-2호", "건축학과 스튜디오6"),
new Room("402호", "건축학과 대학원"),
new Room("402-1호", "건축학과 스튜디오7"),
new Room("402-2호", "건축학과 스튜디오8"),
new Room("403호", "신동윤"),
new Room("404호", "김호정"),
new Room("405호", "강태웅"),
new Room("406호", "이재훈"),
new Room("407호", "정재욱"),
new Room("408호", "성우철"),
new Room("409호", "홍경구"),
new Room("410호", "건축도시기술연구소"),
new Room("411호", "오상훈"),
new Room("412호", "건축학과사무실"),
new Room("413호", "건축학과세미나실"),
new Room("414호", "건축학과 스튜디오9"),
new Room("414-1호", "건축학과 스튜디오10"),
new Room("414-2호", "건축학과 스튜디오11"),
new Room("414-3호", "건축학과 스튜디오12"),
new Room("415호", "전시실"),
new Room("416호", "건축학과 스튜디오13"),
new Room("417호", "건축학과 스튜디오14"),
new Room("417-1호", "건축학과 스튜디오15"),
new Room("418호", "건축학과 스튜디오16"),
new Room("419호", "건축학과 스튜디오17"),
new Room("419-1호", "건축학과 스튜디오18"),
new Room("420호", "건축학과 스튜디오19"),
new Room("421호", "건축학과 스튜디오20"),
new Room("502호", "응용역학실험실1"),
new Room("503호", "광메카트로닉스실험실"),
new Room("504호", "기계CAD실"),
new Room("505호", "교수회의실"),
new Room("506호", "김태정"),
new Room("507호", "최덕기"),
new Room("508호", "배성재"),
new Room("509호", "김영은"),
new Room("510호", "윤경환"),
new Room("511호", "김대근"),
new Room("512호", "지성철"),
new Room("513호", "정성환"),
new Room("514호", "백광현"),
new Room("515호", "세미나실"),
new Room("516호", "CAE설계실험실"),
new Room("517호", "기계공학과사무실"),
new Room("518호", "전산역학실험실"),
new Room("519호", "응용역학실험실2"),
new Room("520호", "신재생에너지실험실"),
new Room("521호", "MEMS 실험"),
new Room("522호", "CAD/CAM실험실"),
new Room("523호", "소음진동실험실"),
new Room("524호", "응용유체실험실"),
new Room("525호", "정밀부품시스템설계 실험실")

                };

                break; //fader.FadeTo("Library"); 
            case "제2 공학관":
                PMS.MoreDetailEnableBoolAnimator(Animator);
                img.sprite = Fengineeringimg;
                buildingname.text = "제2 공학관";
                buildingaddress.text = "경기도 용인시 수지구 죽전로 152(죽전동)";
                RoomList = new ArrayList()
                {
                    new Room("101호", "강의실"),
new Room("102호", "강의실"),
new Room("103호", "공과대학 학생회실"),
new Room("104호", "초고층빌딩 글로벌 R&BD센터 사무국"),
new Room("105호", "강의실"),
new Room("106호", "강의실"),
new Room("107호", "매점"),
new Room("107-1호", "배움터,여울"),
new Room("108호", "건축공학종합설계"),
new Room("109호", "건축설비시스템실험실"),
new Room("110호", "초고층빌딩 글로벌 R&BD센터 회의실"),
new Room("110-2호", "초고층빌딩 글로벌 R&BD센터 자료실"),
new Room("202호", "강의실"),
new Room("203호", "강의실"),
new Room("204호", "강의실"),
new Room("205호", "강의실"),
new Room("206호", "전자전기공학부세미나실"),
new Room("207호", "나경환"),
new Room("208호", "산업기술연구소"),
new Room("209호", "김경호"),
new Room("210호", "남현도"),
new Room("211호", "리보델링연구소/내진보강연구실"),
new Room("212호", "이승기"),
new Room("213호", "이광호"),
new Room("214호", "전자전기기실2"),
new Room("215호", "전자전기공학부사무실"),
new Room("216호", "전자전기공학실험실1"),
new Room("217호", "전자전기공학실험실2"),
new Room("218호", "광전자실험실"),
new Room("221호", "전력시스템연구"),
new Room("222호", "MEMS실험실"),
new Room("0001", "자동심장충격기(입구)"),
new Room("301호", "자율주행드론연구실"),
new Room("302호", "디지털VLSI실험실"),
new Room("303호", "집접회로설계연구실"),
new Room("305호", "신호처리실험준비실"),
new Room("305-1호", "음향실험실"),
new Room("306호", "Human&System Lab"),
new Room("307호", "양재수"),
new Room("308호", "한경호"),
new Room("309호", "강정원"),
new Room("310호", "오승록"),
new Room("311호", "정재훈"),
new Room("312호", "윤석현"),
new Room("313호", "박시흥"),
new Room("314호", "최학근"),
new Room("315호", "전자전기공학전공세미나실"),
new Room("316호", "공과대학 교학행정팀"),
new Room("316-1호", "공과대학 부학장실"),
new Room("317호", "공과대학 학장실"),
new Room("318호", "공학교육혁신센터"),
new Room("319호", "공과대학 세미나실"),
new Room("320호", "CAEC실험준비실"),
new Room("321호", "시스템/제어실험실"),
new Room("322호", "전자전기공학 컴퓨터실습실1"),
new Room("323호", "전자전기공학 컴퓨터실습실3"),
new Room("324호", "전자전기공학 컴퓨터실습실3"),
new Room("325호", "전자전기공학 설계실습준비실2"),
new Room("326호", "전자전기공학 설계실습실2"),
new Room("401호", "파워IC연구실"),
new Room("401-1호", "신호 및 시스템연구실"),
new Room("402호", "영상처리연구실"),
new Room("402-1호", "미래소재연구실"),
new Room("403호", "임베디드 및 병렬시스템연구실"),
new Room("404호", "전자전기 세미나실3"),
new Room("405호", "박선호"),
new Room("406호", "고종선"),
new Room("407호", "어진우"),
new Room("408호", "구용서"),
new Room("409호", "장우영"),
new Room("410호", "방성"),
new Room("411호", "SW품질연구실"),
new Room("412호", "박재형"),
new Room("413호", "에너지 빅데티터 센터"),
new Room("414호", "SoC임베디드시스템 연구실"),
new Room("415호", "정보통신연구실"),
new Room("416호", "광소자연구실"),
new Room("416-1호", "통신시스템 연구실"),
new Room("417호", "반도체설계연구실"),
new Room("418호", "마이크로/나노소자연구실"),
new Room("419호", "디지털설계실험준비실"),
new Room("420호", "디지털설계실습실"),
new Room("421호", "논리회로실험실"),
new Room("422호", "전자전기공학 컴퓨터실습실2"),
new Room("501호", "컴퓨터공학과 실험준비실"),
new Room("502호", "ICT연구센터"),
new Room("503호", "SoC연구실"),
new Room("504호", "알고리즘연구실"),
new Room("505호", "김동수"),
new Room("506호", "최상일"),
new Room("507호", "미래과학기술연구소"),
new Room("508호", "김현진"),
new Room("509호", "김준모"),
new Room("510호", "최천원"),
new Room("511호", "나연묵"),
new Room("512호", "박경신"),
new Room("513호", "김규철"),
new Room("514호", "최용근"),
new Room("515호", "임성한"),
new Room("516호", "응용컴퓨터공학전공사무실"),
new Room("517호", "응용컴퓨터공학세미나실"),
new Room("518호", "자작자동차연구회"),
new Room("519호", "RedBeanz실"),
new Room("520호", "지능형상호작용시스템연구실"),
new Room("521호", "소프트웨어실습실"),
new Room("522호", "임베디드시스템실험실"),
new Room("523호", "강의실"),
new Room("524호", "강의실"),
new Room("525호", "기계학습 및 패턴분석연구실"),
new Room("526호", "DCNL"),
new Room("527호", "데이터통신연구실"),
new Room("528호", "데이터베이스연구실")
                };
                break;
            case "제3 공학관":
                PMS.MoreDetailEnableBoolAnimator(Animator);
                img.sprite = Fengineeringimg;
                buildingname.text = "제3 공학관";
                buildingaddress.text = "경기도 용인시 수지구 죽전동 산 46-2";
                RoomList = new ArrayList()
                {
                    new Room("101호", "창의적공학설계실험실,설계실"),
new Room("102호", "강의실"),
new Room("103호", "강의실"),
new Room("104호", "강의실"),
new Room("105호", "강의실"),
new Room("106호", "강의실"),
new Room("107호", "메이커 스페이스 제작실"),
new Room("108호", "강의실"),
new Room("109호", "강의실"),
new Room("110호", "강의실"),
new Room("111호", "거보신석주강의"),
new Room("202호", "광전기화학에너지실험실"),
new Room("203호", "유기공업화학연구실"),
new Room("204호", "화공기초실험실"),
new Room("205호", "환경분석실험실"),
new Room("206호", "중앙기기실"),
new Room("207호", "화학공학시약실"),
new Room("208호", "실험준비실/화학공학"),
new Room("209호", "화학공학과세미나실"),
new Room("210호", "재료화학시험연구소"),
new Room("211호", "김재엽"),
new Room("212호", "윤용수"),
new Room("213호", "이우걸"),
new Room("214호", "홍인권"),
new Room("215호", "김형수"),
new Room("216호", "심재우"),
new Room("217호", "화학공학과사무실"),
new Room("218호", "열역학연구실"),
new Room("219호", "생체계면조직공학연구실1"),
new Room("220호", "생체계면조직공학연구실2"),
new Room("221호", "환경시스템공학실험실"),
new Room("222호", "정밀화학연구실"),
new Room("223호", "공정설계연구"),
new Room("224호", "반도체소자공정연구실"),
new Room("224-1호", "열역학연구실"),
new Room("225호", "고분자재료연구실1"),
new Room("226호", "고분자재료연구실2"),
new Room("227호", "나노바이오모델링연구실"),
new Room("301호", "파이버시스템공학과세미나"),
new Room("302호", "파이버소재실험실"),
new Room("303호", "고성능파이버연구실"),
new Room("304호", "파이버개질연구실"),
new Room("305호", "파이버분석실험실"),
new Room("305-1호", "초자실"),
new Room("305-2호", "암실"),
new Room("305-3호", "현미경"),
new Room("306호", "파이버시스템공학과사무실"),
new Room("307호", "김호동"),
new Room("308호", "보호복연구소"),
new Room("309호", "송영석"),
new Room("310호", "윤기종"),
new Room("311호", "이정진"),
new Room("312호", "오경근"),
new Room("313호", "김영수"),
new Room("314호", "파이버시스템공학과 창의세미나"),
new Room("315호", "파이버물리실험실"),
new Room("315-1호", "파이버물리준비실"),
new Room("316-1호", "파이버조립실험실"),
new Room("317호", "고기능습식공정실험실"),
new Room("318호", "강의실"),
new Room("319호", "강의실"),
new Room("320호", "화학공학실험실"),
new Room("321호", "에너환경정촉매연구"),
new Room("316-1호", "기능성색소연구실"),
new Room("00001", "자동심장충격기(입구)"),
new Room("401호", "고분자기초실험실"),
new Room("402-1호", "미래소재연구실"),
new Room("403호", "나노기능성소재연구실1"),
new Room("404호", "나노기능성소재연구실2"),
new Room("405호", "종합공학실험실"),
new Room("406호", "고분자공학과사무실"),
new Room("407호", "조준한"),
new Room("408호", "김응건"),
new Room("409호", "강호종"),
new Room("410호", "김오영"),
new Room("411호", "황석호"),
new Room("412호", "오준균"),
new Room("413호", "이동현"),
new Room("414호", "고분자공학과세미나실"),
new Room("415호", "고분자가공실험실"),
new Room("416호", "고분자가공실험준비실"),
new Room("417호", "계산유기반도체실"),
new Room("418호", "일반화학실험실"),
new Room("419호", "고분자기기분석"),
new Room("420호", "고분자 분자모델링 연구"),
new Room("421호", "유기전자소재연구실"),
new Room("422호", "과사랑"),
new Room("423호", "고분자종합설계씰습실"),
new Room("424-1호", "고분자재료전산설계실"),
new Room("402-1호", "재료화학실험실2"),
new Room("424-1", "고분자재료설계실습실"),
new Room("502호", "강의실"),
new Room("503호", "강의실"),
new Room("504호", "강의실"),
new Room("505호", "강의실"),
new Room("506호", "로버트바일"),
new Room("507호", "이승범"),
new Room("508호", "진병두"),
new Room("509호", "독고석"),
new Room("510호", "장수환"),
new Room("511호", "이용걸"),
new Room("512호", "이원준"),
new Room("513호", "김승훈"),
new Room("514호", "이환규"),
new Room("515호", "강의실"),
new Room("516호", "강의실"),
new Room("517호", "강의실"),
new Room("518호", "강의실"),
new Room("519호", "PC강의실"),
new Room("520호", "PC강의실"),
new Room("521호", "PC강의실"),
new Room("522호", "PC강의실")
                };
                break;
            case "사회과학관":
                PMS.MoreDetailEnableBoolAnimator(Animator);
                img.sprite = Fengineeringimg;
                buildingname.text = "사회과학관";
                buildingaddress.text = "경기도 용인시 수지구 죽전로 152(죽전동)";
                RoomList = new ArrayList()
                {
                    new Room("B101호", "PC공동실습실"),
new Room("B102호", "사회과학대학 학생회실"),
new Room("B104호", "참고열람실"),
new Room("B105호", "행정학전공세미나실"),
new Room("B106호", "매점"),
new Room("B106-1호", "복사실"),
new Room("B108호", "강의실"),
new Room("B109호", "강의실"),
new Room("B111호", "정치외교학과세미나실"),
new Room("B112호", "도시계획부동산학부세미나실1"),
new Room("B113호", "도시계획부동산학부세미나실2"),
new Room("101호", "강의실"),
new Room("102호", "부동산학전공사무실"),
new Room("103호", "정치외교학과사무실"),
new Room("104호", "행정학과사무실"),
new Room("105호", "강의실"),
new Room("106호", "강의실"),
new Room("0001", "자동심장충격기(입구)"),
new Room("201호", "교강사휴게실"),
new Room("202호", "도시부동산연구소"),
new Room("203호", "융합사회연구소"),
new Room("204호", "사회과학대학장실"),
new Room("205호", "송운석"),
new Room("206호", "남재걸"),
new Room("207호", "김성종"),
new Room("208호", "류지성"),
new Room("209호", "사회과학대학 교학행정팀"),
new Room("210호", "김재일"),
new Room("211호", "박용성"),
new Room("212호", "정창화"),
new Room("213호", "김형수"),
new Room("215호", "강의실(계단강의실)"),
new Room("215-1호", "영사실"),
new Room("301호", "강의실"),
new Room("302호", "강의실"),
new Room("303호", "강의실"),
new Room("304호", "강의실"),
new Room("305호", "강의실"),
new Room("306호", "도시지역계획학사무실"),
new Room("307호", "강의실"),
new Room("308호", "도시계획CAD실"),
new Room("401호", "김병량"),
new Room("402호", "조명래"),
new Room("404호", "가상준"),
new Room("405호", "안순철"),
new Room("406호", "김진호"),
new Room("408호", "조한승"),
new Room("409호", "이동민"),
new Room("410호", "고석찬"),
new Room("411호", "김호철"),
new Room("412호", "송명규"),
new Room("413호", "김현수"),
new Room("414호", "이혜경"),
new Room("415호", "이호병"),
new Room("416호", "유정석"),
new Room("417호", "우석한국영토연구소"),
new Room("417-1호", "우석한국영토연구소장실")
                };
                break;
            case "범정관":
                PMS.MoreDetailEnableBoolAnimator(Animator);
                img.sprite = Mainimg;
                buildingname.text = "범정관";
                buildingaddress.text = "경기도 용인시 수지구 죽전로 152(죽전동)";
                RoomList = new ArrayList()
                {
                    new Room("0001호", "현금지급기(우리)"),
new Room("101호", "수위실"),
new Room("102호", "회의실(14실)"),
new Room("103호", "입학처장실"),
new Room("104호", "입학팀(105호 통합)"),
new Room("105호", "입학팀"),
new Room("106호", "입학카운슬링센터/회의실"),
new Room("107호", "자산관리팀"),
new Room("112호", "CS경영팀"),
new Room("113호", "CS경영센터장실"),
new Room("114호", "재무회계팀"),
new Room("117호", "학사팀"),
new Room("117-1호", "미래교육혁신원"),
new Room("118호", "단소리CS센터"),
new Room("0002호", "자동심장충격기(경비실옆)"),
new Room("0003호", "자동심장충격기(계단옆)"),
new Room("201호", "안전관리팀"),
new Room("202호", "총무인사처 부처장실"),
new Room("203호", "총무인사팀"),
new Room("204호", "총무처장실"),
new Room("206호", "회의실상담실"),
new Room("207호", "대외협력팀"),
new Room("208호", "대외협력처장실"),
new Room("209호", "홍보팀"),
new Room("210호", "교무위원실"),
new Room("301호", "예산팀"),
new Room("302호", "기획실장실"),
new Room("303호", "전략사업팀"),
new Room("304호", "기획평가"),
new Room("305호", "비서실장실"),
new Room("305-1호", "비서실장실"),
new Room("306호", "총장비서실"),
new Room("307호", "총장실"),
new Room("309호", "이사장실"),
new Room("311호", "이사장비서실"),
new Room("312호", "회의실"),
new Room("313호", "회의실(314호 통합)"),
new Room("315호", "법인 사무처"),
new Room("316호", "법인 경리팀"),
new Room("317호", "법인 사무처장실"),
new Room("319호", "교학부총장실"),
new Room("320호", "교학부총장비서실"),
new Room("321호", "대외부총장실"),
new Room("322호", "부총장비서실"),
new Room("323호", "산학부총장실"),
new Room("304-1호", "기획실 부처장실"),
new Room("401-1호", "콜센터"),
new Room("401-2호", "수유실"),
new Room("402호", "정보기획팀"),
new Room("405호", "정보통신상황실"),
new Room("406호", "정보인프라팀"),
new Room("407호", "정보화기획센터장실"),
new Room("409호", "회의실"),
new Room("501호", "교무팀"),
new Room("503호", "교무처장실"),
new Room("504호", "연구팀"),
new Room("504-1호", "법무감사팀"),
new Room("505호", "대회의실"),
new Room("507호", "교육성과평가센터 사무실"),
new Room("508호", "미래교육혁신원장실"),
new Room("509호", "특임부총장실"),
new Room("510호", "미래교육1팀"),
new Room("511호", "통신실")
                };
                break;


                }
        foreach (Room room in RoomList)
        {
            GameObject newRoom = Instantiate(ListItemPrefab) as GameObject;
            ListItemController controller = newRoom.GetComponent<ListItemController>();
            controller.Room.text = room.room;
            controller.RoomName.text = room.roomname;
            newRoom.transform.parent = ContentPanel.transform;
            newRoom.transform.localScale = Vector3.one;
        }
    }
}
